routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return redirect()->route('home');
    });

    Route::prefix('admin')->group(function () {
        Route::resource('users', App\Http\Controllers\UserController::class);
        Route::resource('roles', App\Http\Controllers\RoleController::class);
        Route::resource('permissions', App\Http\Controllers\PermissionController::class);
    });

    Route::resource('profile', App\Http\Controllers\ProfileController::class)->only(['edit', 'update']);
    Route::resource('password', App\Http\Controllers\ChangePasswordController::class)->only(['edit', 'update']);
});

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Permission extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['name'];
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Gate;
use App\Models\Permission;
use App\DataTables\PermissionDataTable;
use App\Http\Requests\PermissionRequest;
use Symfony\Component\HttpFoundation\Response;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PermissionDataTable $dataTable)
    {
        abort_if(Gate::denies('permission_access'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        return $dataTable->render('pages.permissions.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('permission_create'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        return view('pages.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\PermissionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionRequest $request)
    {
        Permission::create($request->validated());
        return redirect()->route('permissions.index')->with('success', MESSAGE_SAVED);
    }

    /**
     * Display the specified resource.
     *
     * @param  Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function show(Permission $permission)
    {
        abort_if(Gate::denies('permission_show'), Response::HTTP_FORBIDDEN, FORBIDDEN);
        return view('pages.permissions.show', compact('permission'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        abort_if(Gate::denies('permission_edit'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        return view('pages.permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\PermissionRequest  $request
     * @param  Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionRequest $request, Permission $permission)
    {
        $permission->update($request->validated());
        return redirect()->route('permissions.index')->with('success', MESSAGE_UPDATED);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        abort_if(Gate::denies('permission_delete'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        $permission->delete();
        return redirect()->route('permissions.index')->with('success', MESSAGE_DELETED);
    }
}

resources/views/pages/permissions/create.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
      title="Permissions" 
      icon="lock" 
      parent="permissions.index" 
      :breadcrumbs="[
                'page' => 'Create Permission'
      ]" 
      :button="[]" 
/>

<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button label="Save" />
              
              <div class="card-body">
                  <form id="form_id" action="{{ route('permissions.store') }}" method="POST">
                      @csrf
                      <div class="pl-lg-4">
                          <x-form-input type="text" name="name" label="Name" required="required"/>
                      </div>
                      <hr class="my-4" />
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endsection

resources/views/pages/permissions/edit.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
    icon="lock" 
    title="Permission" 
    parent="permissions.index" 
    :breadcrumbs="[
        'page' => 'Edit Permission'
    ]" 
    :button="[]" />

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-xl-8 order-xl-1">
            <div class="card">

                <x-card-header-button label="Update" />
                
                <div class="card-body">
                    <form id="form_id" action="{{ route('permissions.update', $permission->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="pl-lg-4">
                            <x-form-input type="text" name="name" label="Name" required="required" value="{{ $permission->name }}"/>
                        </div>
                        <hr class="my-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/permissions/index.blade.php
@extends('layouts.app')

@section('content')
<x-breadcrumb 
    title="Permissions" 
    icon="lock"  
    :breadcrumbs="[
        'page' => 'Permissions'
    ]"
    :button="[
        'route' => 'permissions.create',
        'label' => 'Create Permission'
    ]" 
/>

<x-card-datatables title="Permissions" :datatable="$dataTable" />

@endsection

resources/views/pages/permissions/show.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
      title="Permission" 
      icon="tasks" 
      parent="permissions.index" 
      :breadcrumbs="[
                'page' => 'Show Permission'
      ]" 
      :button="[]" 
/>


<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button />
              
              <div class="card-body">
                <h5 class="text-muted mb-4">{{ $permission->name }}</h5>
                <hr class="my-4" />
              </div>
          </div>
      </div>
  </div>
</div>

@endsection