routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return redirect()->route('home');
    });

    Route::prefix('admin')->group(function () {
        Route::resource('users', App\Http\Controllers\UserController::class);
        Route::resource('roles', App\Http\Controllers\RoleController::class);
        Route::resource('permissions', App\Http\Controllers\PermissionController::class);
    });

    Route::resource('profile', App\Http\Controllers\ProfileController::class)->only(['edit', 'update']);
    Route::resource('password', App\Http\Controllers\ChangePasswordController::class)->only(['edit', 'update']);
});

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Gate;

use App\Models\User;
use App\Models\Role;
use App\DataTables\UserDataTable;
use App\Http\Requests\UserRequest;
use Symfony\Component\HttpFoundation\Response;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UserDataTable $dataTable)
    {
        return $dataTable->render('pages.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::select('id', 'name')->get();
        return view('pages.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $user = User::create($request->validated());
        $user->roles()->sync($request->input('role_id', []));
        return redirect()->route('users.index')->with('success', 'Data saved successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('pages.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::select('id', 'name')->get();
        return view('pages.users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        $user->update($request->all());
        $user->roles()->sync($request->input('role_id', []));

        return redirect()->route('users.index')->with('success', 'Data updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        abort_if(Gate::denies('user_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $user->delete();

        return redirect()->route('users.index')->with('success', 'Data deleted successfully');
    }
}

resources/views/pages/users/create.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
  icon="user" 
  title="Users" 
  parent="users.index" 
  :breadcrumbs="[
    'page' => 'Create User'
  ]" 
  :button="[]" 
/>


<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button label="Save"/>

              <div class="card-body">
                  <form id="form_id" action="{{ route('users.store') }}" method="POST">
                      @csrf
                      <div class="pl-lg-4">

                          <x-form-input type="text" name="name" label="Name" required="required"/>
                          <x-form-input type="email" name="email" label="Email" required="required"/>
                          <x-form-input type="password" name="password" label="Password" required="required"/>
                          <x-form-input type="password" name="password_confirmation" label="Confirmation Password" required="required"/>
                          <x-form-select name="role_id" label="Role" required="required" :values="$roles"/>

                      <hr class="my-4" />
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
    });
</script> 
@endpush

resources/views/pages/users/edit.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
  icon="user" 
  title="Users" 
  parent="users.index" 
  :breadcrumbs="[
    'page' => 'Edit User'
  ]" 
  :button="[]" 
/>


<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button label="Update"/>

              <div class="card-body">
                  <form id="form_id" action="{{ route('users.update', $user->id) }}" method="POST">
                      @csrf
                      @method('PUT')
                      <div class="pl-lg-4">
                          <p>{{ $user->role_id }}</p>
                          <x-form-input type="text" name="name" label="Nama" required="required" value="{{ $user->name }}"/>
                          <x-form-input type="email" name="email" label="Email" required="required" value="{{ $user->email }}"/>
                          <x-form-select name="role_id" label="Role" required="required" :values="$roles" :selected="$user->roles->first()->id"/>

                      </div>
                      <hr class="my-4" />
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>

@endsection

resources/views/pages/users/index.blade.php
@extends('layouts.app')

@section('content')
<x-breadcrumb 
    title="User" 
    icon="user"  
    :breadcrumbs="[
        'page' => 'Users'
    ]"
    :button="[
        'route' => 'users.create',
        'label' => 'Create User'
    ]" 
/>

<x-card-datatables title="Users" :datatable="$dataTable" />

@endsection

resources/views/pages/users/show.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
      title="Users" 
      icon="user" 
      parent="users.index" 
      :breadcrumbs="[
                'page' => 'Show User'
      ]" 
      :button="[]" 
/>


<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button />
              
              <div class="card-body">
                <h5 class="text-muted mb-4">{{ 'Name : '.$user->name }}</h5>
                <h5 class="text-muted mb-4">{{ 'Email : '.$user->email }}</h5>
                <h5 class="text-muted mb-4">{{ 'Role : ' }}</h5>
                <ul>
                    @forelse ($user->roles as $role)
                        <li>{{ $role->name }}</li>
                    @empty
                        <li>No record for roles</li>
                    @endforelse
                </ul>            
                <hr class="my-4" />
              </div>
          </div>
      </div>
  </div>
</div>

@endsection