routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return redirect()->route('home');
    });

    Route::prefix('admin')->group(function () {
        Route::resource('users', App\Http\Controllers\UserController::class);
        Route::resource('roles', App\Http\Controllers\RoleController::class);
        Route::resource('permissions', App\Http\Controllers\PermissionController::class);
    });

    Route::resource('profile', App\Http\Controllers\ProfileController::class)->only(['edit', 'update']);
    Route::resource('password', App\Http\Controllers\ChangePasswordController::class)->only(['edit', 'update']);
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['name'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Gate;

use App\Models\Role;
use App\Models\Permission;
use App\DataTables\RolesDataTable;
use App\Http\Requests\RoleRequest;
use Symfony\Component\HttpFoundation\Response;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(RolesDataTable $dataTable)
    {
        abort_if(Gate::denies('role_access'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        return $dataTable->render('pages.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('role_create'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        $roles = Role::select('id', 'name')->with('permissions')->get();
        return view('pages.roles.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RoleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        $role = Role::create($request->validated());
        $role->permissions()->sync($request->input('permissions', []));
        return redirect()->route('roles.index')->with('success', MESSAGE_SAVED);
    }

    /**
     * Display the specified resource.
     *
     * @param  Role $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        abort_if(Gate::denies('role_show'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        return view('pages.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Role $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        abort_if(Gate::denies('role_edit'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        $role->load('permissions');
        $permissions = Permission::pluck('name', 'id');
        return view('pages.roles.edit', compact('permissions', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\RoleRequest  $request
     * @param  Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(RoleRequest $request, Role $role)
    {
        $role->update($request->validated());
        $role->permissions()->sync($request->input('permissions', []));
        return redirect()->route('roles.index')->with('success', MESSAGE_UPDATED);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Role $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        abort_if(Gate::denies('role_delete'), Response::HTTP_FORBIDDEN, FORBIDDEN);

        $role->delete();
        return redirect()->route('roles.index')->with('success', MESSAGE_DELETED);
    }
}

resources/views/pages/roles/create.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
      title="Roles" 
      icon="tasks" 
      parent="roles.index" 
      :breadcrumbs="[
                'page' => 'Create Role'
      ]" 
      :button="[]" 
/>

<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button label="Save" />
              
              <div class="card-body">
                  <form id="form_id" action="{{ route('roles.store') }}" method="POST">
                      @csrf
                      <div class="pl-lg-4">
                          <x-form-input type="text" name="name" label="Name" required="required"/>
                      </div>
                      <hr class="my-4" />
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endsection

resources/views/pages/roles/edit.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
    icon="tasks" 
    title="Role" 
    parent="roles.index" 
    :breadcrumbs="[
        'page' => 'Edit Role'
    ]" 
    :button="[]" />

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-xl-8 order-xl-1">
            <div class="card">

                <x-card-header-button label="Update" />
                
                <div class="card-body">
                    <form id="form_id" action="{{ route('roles.update', $role->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="pl-lg-4">
                            <x-form-input type="text" name="name" label="Name" required="required" value="{{ $role->name }}"/>
                        </div>
                        <hr class="my-4" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/roles/index.blade.php
@extends('layouts.app')

@section('content')
<x-breadcrumb 
    title="Roles" 
    icon="tasks"  
    :breadcrumbs="[
        'page' => 'Roles'
    ]"
    :button="[
        'route' => 'roles.create',
        'label' => 'Create Role'
    ]" 
/>

<x-card-datatables title="Roles" :datatable="$dataTable" />

@endsection

resources/views/pages/roles/show.blade.php
@extends('layouts.app')

@section('content')

<x-breadcrumb 
      title="Roles" 
      icon="tasks" 
      parent="roles.index" 
      :breadcrumbs="[
                'page' => 'Show Role'
      ]" 
      :button="[]" 
/>


<div class="container-fluid mt-5">
  <div class="row">
      <div class="col-xl-8 order-xl-1">
          <div class="card">
              
              <x-card-header-button />
              
              <div class="card-body">
                <h5 class="text-muted mb-4">{{ $role->name }}</h5>

                <ul>
                @forelse ($role->permissions as $permission)
                    <li>{{ $permission->name }}</li>
                @empty
                    <li>No record for permissions</li>
                @endforelse
                </ul>
                <hr class="my-4" />
              </div>
          </div>
      </div>
  </div>
</div>

@endsection